# Generated by Django 5.2 on 2026-09-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Administrador', 'Administrador'), ('Operador', 'Operador'), ('Supervisor', 'Supervisor')], default='Operador', max_length=20),
        ),
    ]
