# Generated by Django 5.2 on 2025-04-19 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nombre de la Categoría",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=255, verbose_name="Marca del Producto"),
                ),
                (
                    "name",
                    models.CharField(max_length=61, verbose_name="Nombre del Producto"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product/", verbose_name="Imagen del Producto"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "product_of_stock",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
        ),
    ]
