# Generated by Django 5.1.1 on 2025-05-13 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="bulk_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio por paquete",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="bulk_unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_por_paquete",
                to="products.unidadmedida",
                verbose_name="Unidad de paquete",
            ),
        ),
    ]
