# Generated by Django 5.1.1 on 2025-04-24 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nombre Unidad de Medidad",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="producto",
            name="price",
        ),
        migrations.AddField(
            model_name="producto",
            name="bulk_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio por paquete",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio por unidad",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producto",
            name="name",
            field=models.CharField(max_length=55, verbose_name="Nombre del Producto"),
        ),
        migrations.AddField(
            model_name="producto",
            name="bulk_unit_of_measure",
            field=models.ForeignKey(
                default="unit",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_por_paquete",
                to="products.unidadmedida",
                verbose_name="Unidad de paquete",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="unit_of_measure",
            field=models.ForeignKey(
                default="kg",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_por_unidad",
                to="products.unidadmedida",
                verbose_name="Unidad de medida",
            ),
            preserve_default=False,
        ),
    ]
