# Generated by Django 5.2 on 2025-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_producto_bulk_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="name_normalized",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="producto",
            name="brand_normalized",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="producto",
            name="name_normalized",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
