# Generated by Django 5.2 on 2025-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_categoria_name_normalized_producto_brand_normalized_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="name_normalized",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="brand_normalized",
        ),
        migrations.AlterField(
            model_name="producto",
            name="name_normalized",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
