# Generated by Django 5.2 on 2025-05-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_categoria_name_normalized_producto_brand_normalized"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="name_normalized",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="brand_normalized",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="name_normalized",
        ),
    ]
