# Generated by Django 5.1.1 on 2025-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_categoria_name_normalized_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=100, unique=True)),
                ("visits", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
