# Generated by Django 5.1.1 on 2025-10-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_visitcounter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitcounter",
            options={
                "verbose_name": "Contador de visitas",
                "verbose_name_plural": "Contador de visitas",
            },
        ),
        migrations.AlterField(
            model_name="visitcounter",
            name="page_name",
            field=models.CharField(max_length=255, verbose_name="Página"),
        ),
        migrations.AlterField(
            model_name="visitcounter",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="Visitas"),
        ),
    ]
