# Generated by Django 5.1.1 on 2025-10-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_visitcounter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitcounter",
            options={
                "verbose_name": "Ver visitas",
                "verbose_name_plural": "Ver visitas",
            },
        ),
    ]
