# Generated by Django 5.1.1 on 2025-11-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_visitcounter_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=255, verbose_name="Página")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de visita",
                "verbose_name_plural": "Registros de visitas",
            },
        ),
    ]
