# Generated by Django 5.1.1 on 2025-11-23 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_visitlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VisitLog",
        ),
        migrations.AddField(
            model_name="visitcounter",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visitcounter",
            unique_together={("page_name", "date")},
        ),
    ]
