# Generated by Django 5.2 on 2026-09-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_producto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='catalogos_pdf/')),
                ('productos_hash', models.CharField(db_index=True, max_length=64)),
                ('total_productos', models.PositiveIntegerField(default=0)),
                ('generado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo PDF',
                'verbose_name_plural': 'Catálogos PDF',
            },
        ),
    ]
