# Generated by Django 5.2 on 2026-09-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_catalogopdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('processed_products', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='catalogos_pdf/jobs/')),
                ('tamano_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trabajo de generación de PDF',
                'verbose_name_plural': 'Trabajos de generación de PDF',
                'ordering': ['-created_at'],
            },
        ),
    ]
