# Generated by Django 5.2 on 2026-09-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_pdfgenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible en el catálogo'),
        ),
    ]
