# Generated by Django 5.2 on 2026-09-26 06:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_producto_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogopdf',
            name='tamano_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogopdf',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='catalogos_pdf/'),
        ),
        migrations.AlterField(
            model_name='pdfgenerationjob',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='catalogos_pdf/jobs/'),
        ),
    ]
