# Generated by Django 5.2 on 2026-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_catalogopdf_tamano_bytes_alter_catalogopdf_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfgenerationjob',
            name='descargado',
            field=models.BooleanField(default=False),
        ),
    ]
