# Generated by Django 5.2 on 2026-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_pdfgenerationjob_descargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_historial_mb', models.PositiveIntegerField(default=5)),
                ('dias_expiracion', models.PositiveIntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Configuración de catálogos PDF',
                'verbose_name_plural': 'Configuración de catálogos PDF',
            },
        ),
    ]
