# Generated by Django 5.2 on 2026-09-27 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_configuracionpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255, verbose_name='Página')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP del visitante')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de visita (IP)',
                'verbose_name_plural': 'Registros de visita (IP)',
                'unique_together': {('page_name', 'ip_address', 'date')},
            },
        ),
    ]
